package com.example.taskflow.entities;

public enum EnumCategory {
    FEATURE, BUG, IMPROVEMENT, TECHNICAL_DEBT, TESTING, DOCUMENTATION,
    REFACTOR, MAINTENANCE, RESEARCH, SUPPORT, DESIGN, MEETING, TRAINING, DEPLOYMENT
}
